[komga]
# Komga URL
url = "http://localhost:25600"
# Title to use for Komga Site
site_title = "Komga"

[newsletters]
enabled = true
# Default templates directory
templates_dir = "templates"
# Default rendered newsletters directory
content_dir = "newsletters"
# Default newsletter URL, if used outside your local network, be sure to configure this to an external URL
url = "http://localhost:8000"
# Default newsletter Discord channel
channel = "general"
# Newsletter notification schedule. Default is every Wednesday at 11:00 AM
# format is different from standard CRON:
#                  sec   min   hour   day of month   month   day of week   year
schedule = "0 0 11 * * Wed *"


[stats]
enabled = true
# Category to use for stats
category = "Comics Stats"
# Stats update schedule. Default is every Wednesday at 11:00 AM
# format is different from standard CRON:
#                  sec   min   hour   day of month   month   day of week   year
schedule = "0 5 * * * * *"