image:
  repository: spiegela/komga-discord-bot
  pullPolicy: IfNotPresent
  tag: 0.1.1

komga:
  url:
  username:
  password:
  libraries:

discord:
  token:

newsletters:
  url:

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ROCKET_ADDRESS: 0.0.0.0

service:
  main:
    ports:
      main:
        port: 8000

persistence:
  newsletters:
    enabled: true
    type: pvc
    objectName: main
    expandObjectName: true
    optional: false
    defaultMode: "0755"
    mountPath: /newsletters
  config:
    enabled: true
    type: secret
    objectName: main
    expandObjectName: true
    optional: false
    defaultMode: "0755"
    mountPath: /config

portal:
  open:
    enabled: false

secret:
  main:
    expandObjectName: true
    enabled: true
    data:
      default.toml: |-
        [komga]
        # Komga URL
        url = "http://localhost:25600"
        # Title to use for Komga Site
        site_title = "Komga"
        [newsletters]
        enabled = true
        # Default templates directory
        templates_dir = "templates"
        # Default rendered newsletters directory
        content_dir = "newsletters"
        # Default newsletter URL, if used outside your local network, be sure to configure this to an external URL
        url = "http://localhost:8000"
        # Default newsletter Discord channel
        channel = "general"
        # Newsletter notification schedule. Default is every Wednesday at 11:00 AM
        # format is different from standard CRON:
        #                  sec   min   hour   day of month   month   day of week   year
        schedule = "0 0 11 * * Wed *"
        [stats]
        enabled = true
        # Category to use for stats
        category = "Comics Stats"
        # Stats update schedule. Default is every Wednesday at 11:00 AM
        # format is different from standard CRON:
        #                  sec   min   hour   day of month   month   day of week   year
        schedule = "0 5 * * * * *"
      local.toml: |-
        [komga]
        url = {{ .Values.komga.url | required "komga.url is required" | quote }}
        username = {{ .Values.komga.username | required "komga.username is required" | quote }}
        password = {{ .Values.komga.password | required "komga.password is required" | quote }}
        {{- if .Values.komga.libraries }}
        libraries = [{{- range $index, $element := .Values.komga.libraries }}
          {{- if $index }}, {{- end }}
          {{- $element | quote }}
        {{- end }}]
        {{- end }}
        [discord]
        token = {{ .Values.discord.token | required "discord.token is required" | quote }}
        {{- if .Values.discord.role }}
        role = {{ .Values.discord.role | quote }}
        {{- end }}
        [newsletters]
        url = {{ .Values.newsletters.url | required "newsletters.url is required" | quote }}

resources:
  limits:
    cpu: 1000m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 100Mi

ixChartContext:
  addNvidiaRuntimeClass: false
  hasNFSCSI: true
  hasSMBCSI: true
  isInstall: true
  isUpdate: false
  isUpgrade: false
  kubernetes_config:
    cluster_cidr: 172.16.0.0/16
    cluster_dns_ip: 172.17.0.10
    service_cidr: 172.17.0.0/16
  nfsProvisioner: nfs.csi.k8s.io
  nvidiaRuntimeClassName: nvidia
  operation: UPDATE
  smbProvisioner: smb.csi.k8s.io